version: '2'
services:
  nginx:
    build: ./docker/nginx
    container_name: blog-nginx
    volumes:
      - ./src/.vuepress/dist:/var/www
    environment:
      VIRTUAL_HOST: to-hutohu.com
      LETSENCRYPT_HOST: to-hutohu.com
      LETSENCRYPT_EMAIL: tohu.soy@gmail.com
    restart: always
networks:
  default:
    external:
      name: docker-nginx_default
